# Generated by Django 4.2.7 on 2023-11-17 07:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('userEmail', models.EmailField(max_length=254)),
                ('surveyFileName', models.CharField(max_length=255)),
                ('resultFileName', models.CharField(max_length=255)),
                ('rowNumber', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
