# Generated by Django 4.2.7 on 2023-11-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacter_identification', '0002_survey_userhash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='userHash',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
