# Generated by Django 4.2.7 on 2023-11-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacter_identification', '0004_alter_survey_userhash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bacteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('spectrum', models.TextField()),
            ],
        ),
    ]
