# Generated by Django 4.2.7 on 2023-11-24 07:50

import bacter_identification.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacter_identification', '0006_auto_20231123_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='number',
            field=models.CharField(default='AA00000000', max_length=10, unique=True, validators=[bacter_identification.models.validate_alpha_numeric]),
        ),
    ]
