# Generated by Django 4.2.7 on 2024-01-18 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bacter_identification', '0010_survey_cnnpredfilename_survey_rnnpredfilename_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='svgPredFileName',
            new_name='svmPredFileName',
        ),
    ]
