# Generated by Django 4.2.7 on 2024-01-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacter_identification', '0011_rename_svgpredfilename_survey_svmpredfilename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='cnnPredFileName',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='rnnPredFileName',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='svmPredFileName',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
