# Generated by Django 4.2.7 on 2024-01-22 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bacter_identification', '0013_remove_survey_resultfilename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='modelTypes',
        ),
    ]
