# Generated by Django 4.2.7 on 2024-01-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacter_identification', '0014_remove_survey_modeltypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='modelTypes',
            field=models.JSONField(default=['CNN']),
        ),
    ]
