# Generated by Django 4.2.7 on 2024-01-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacter_identification', '0015_survey_modeltypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='modelTypes',
            field=models.JSONField(default=dict),
        ),
    ]
