# Generated by Django 5.0.3 on 2024-05-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacter_identification', '0016_alter_survey_modeltypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='merch_id',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
