# Generated by Django 5.0.3 on 2024-05-13 11:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacter_identification', '0017_survey_merch_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_id', models.CharField(max_length=255)),
                ('merch_id', models.CharField(blank=True, max_length=7)),
                ('employee_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cnn_result', models.JSONField(default=dict, null=True)),
                ('svm_result', models.JSONField(default=dict, null=True)),
                ('rnn_result', models.JSONField(default=dict, null=True)),
            ],
        ),
    ]
