# Generated by Django 4.2.7 on 2023-11-16 07:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userauth',
            options={},
        ),
        migrations.AlterModelManagers(
            name='userauth',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='userauth',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='userauth',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userauth',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='userauth',
            name='last_name',
        ),
        migrations.AddField(
            model_name='userauth',
            name='corporateName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userauth',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userauth',
            name='corporateId',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='userauth',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='userauth',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userauth',
            name='username',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
