# Generated by Django 4.2.7 on 2023-11-17 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_userauth_options_alter_userauth_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauth',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
