# Generated by Django 4.2.7 on 2023-11-17 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_survey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Survey',
        ),
    ]
