# Generated by Django 4.2.7 on 2023-11-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_delete_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauth',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
