# Generated by Django 5.0.3 on 2024-04-24 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_merchantadmin_merchantemployee_systemadmin_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAuth',
        ),
    ]
