# Generated by Django 5.0.3 on 2024-04-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_delete_userauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantadmin',
            name='user_type',
            field=models.CharField(choices=[('SA', 'System Admin'), ('DA', 'Django Admin'), ('MA', 'Merchant Admin'), ('ME', 'Merchant Employee')], default='MA', max_length=2),
        ),
        migrations.AddField(
            model_name='merchantemployee',
            name='user_type',
            field=models.CharField(choices=[('SA', 'System Admin'), ('DA', 'Django Admin'), ('MA', 'Merchant Admin'), ('ME', 'Merchant Employee')], default='ME', max_length=2),
        ),
    ]
