# Generated by Django 5.0.3 on 2024-04-24 07:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_merchantadmin_user_type_merchantemployee_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemadmin',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
